### ISSUE TITLE
median(1) returns Numeric instead of NArray

### ISSUE THREAD

**Issue by gbuesing** [masa16/narray#45]
AFAICT median(1) is behaving incorrectly, because it returns a Numeric instead of NArray:

```
irb(main):001:0> a = NArray[[1,2],[4,5]].to_f
=> NArray.sfloat(2,2): 
[ [ 1.0, 2.0 ], 
  [ 4.0, 5.0 ] ]
irb(main):002:0> a.mean
=> 3.0
irb(main):003:0> a.median
=> 3.0
irb(main):004:0> a.mean 0
=> NArray.sfloat(2): 
[ 1.5, 4.5 ]
irb(main):005:0> a.median 0
=> NArray.sfloat(2): 
[ 1.5, 4.5 ]
irb(main):006:0> a.mean 1
=> NArray.sfloat(2): 
[ 2.5, 3.5 ]
irb(main):007:0> a.median 1
=> 3.0
```

My work-around is to use ``rot90.median(0)``, which returns what I'd expect median(1) to return:

```
irb(main):008:0> a.rot90.median(0)
=> NArray.sfloat(2): 
[ 2.5, 3.5 ]
```

**Comment by masa16** [comment]
This behavior is intended as is described in SPEC.en.txt:

    self.median(dim)	 Median in 0..dim (All dimensions if omitted)

The behavior you expect will be achieved in https://github.com/masa16/narray-devel

**Comment by gbuesing** [comment]
Ok thank you!
